package com.dyh.transaction.dao.model;

public class GlobalTransactionProcessWithBLOBs extends GlobalTransactionProcess {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column global_transaction_process.request_json
     *
     * @mbg.generated Tue Dec 05 13:47:12 CST 2017
     */
    private String requestJson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column global_transaction_process.response_json
     *
     * @mbg.generated Tue Dec 05 13:47:12 CST 2017
     */
    private String responseJson;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column global_transaction_process.request_json
     *
     * @return the value of global_transaction_process.request_json
     *
     * @mbg.generated Tue Dec 05 13:47:12 CST 2017
     */
    public String getRequestJson() {
        return requestJson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column global_transaction_process.request_json
     *
     * @param requestJson the value for global_transaction_process.request_json
     *
     * @mbg.generated Tue Dec 05 13:47:12 CST 2017
     */
    public void setRequestJson(String requestJson) {
        this.requestJson = requestJson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column global_transaction_process.response_json
     *
     * @return the value of global_transaction_process.response_json
     *
     * @mbg.generated Tue Dec 05 13:47:12 CST 2017
     */
    public String getResponseJson() {
        return responseJson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column global_transaction_process.response_json
     *
     * @param responseJson the value for global_transaction_process.response_json
     *
     * @mbg.generated Tue Dec 05 13:47:12 CST 2017
     */
    public void setResponseJson(String responseJson) {
        this.responseJson = responseJson;
    }
}