package com.dyh.transaction.dao.model;

import java.util.Date;

public class GlobalTransactionProcess {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column global_transaction_process.id
     *
     * @mbg.generated Tue Dec 05 13:47:12 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column global_transaction_process.transaction_id
     *
     * @mbg.generated Tue Dec 05 13:47:12 CST 2017
     */
    private Integer transactionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column global_transaction_process.transaction_sequence
     *
     * @mbg.generated Tue Dec 05 13:47:12 CST 2017
     */
    private Integer transactionSequence;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column global_transaction_process.status
     *
     * @mbg.generated Tue Dec 05 13:47:12 CST 2017
     */
    private Short status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column global_transaction_process.expected_status
     *
     * @mbg.generated Tue Dec 05 13:47:12 CST 2017
     */
    private Short expectedStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column global_transaction_process.service_name
     *
     * @mbg.generated Tue Dec 05 13:47:12 CST 2017
     */
    private String serviceName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column global_transaction_process.version_name
     *
     * @mbg.generated Tue Dec 05 13:47:12 CST 2017
     */
    private String versionName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column global_transaction_process.method_name
     *
     * @mbg.generated Tue Dec 05 13:47:12 CST 2017
     */
    private String methodName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column global_transaction_process.rollback_method_name
     *
     * @mbg.generated Tue Dec 05 13:47:12 CST 2017
     */
    private String rollbackMethodName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column global_transaction_process.retry_times
     *
     * @mbg.generated Tue Dec 05 13:47:12 CST 2017
     */
    private Integer retryTimes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column global_transaction_process.next_retry_time
     *
     * @mbg.generated Tue Dec 05 13:47:12 CST 2017
     */
    private Date nextRetryTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column global_transaction_process.created_at
     *
     * @mbg.generated Tue Dec 05 13:47:12 CST 2017
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column global_transaction_process.updated_at
     *
     * @mbg.generated Tue Dec 05 13:47:12 CST 2017
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column global_transaction_process.id
     *
     * @return the value of global_transaction_process.id
     *
     * @mbg.generated Tue Dec 05 13:47:12 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column global_transaction_process.id
     *
     * @param id the value for global_transaction_process.id
     *
     * @mbg.generated Tue Dec 05 13:47:12 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column global_transaction_process.transaction_id
     *
     * @return the value of global_transaction_process.transaction_id
     *
     * @mbg.generated Tue Dec 05 13:47:12 CST 2017
     */
    public Integer getTransactionId() {
        return transactionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column global_transaction_process.transaction_id
     *
     * @param transactionId the value for global_transaction_process.transaction_id
     *
     * @mbg.generated Tue Dec 05 13:47:12 CST 2017
     */
    public void setTransactionId(Integer transactionId) {
        this.transactionId = transactionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column global_transaction_process.transaction_sequence
     *
     * @return the value of global_transaction_process.transaction_sequence
     *
     * @mbg.generated Tue Dec 05 13:47:12 CST 2017
     */
    public Integer getTransactionSequence() {
        return transactionSequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column global_transaction_process.transaction_sequence
     *
     * @param transactionSequence the value for global_transaction_process.transaction_sequence
     *
     * @mbg.generated Tue Dec 05 13:47:12 CST 2017
     */
    public void setTransactionSequence(Integer transactionSequence) {
        this.transactionSequence = transactionSequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column global_transaction_process.status
     *
     * @return the value of global_transaction_process.status
     *
     * @mbg.generated Tue Dec 05 13:47:12 CST 2017
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column global_transaction_process.status
     *
     * @param status the value for global_transaction_process.status
     *
     * @mbg.generated Tue Dec 05 13:47:12 CST 2017
     */
    public void setStatus(Short status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column global_transaction_process.expected_status
     *
     * @return the value of global_transaction_process.expected_status
     *
     * @mbg.generated Tue Dec 05 13:47:12 CST 2017
     */
    public Short getExpectedStatus() {
        return expectedStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column global_transaction_process.expected_status
     *
     * @param expectedStatus the value for global_transaction_process.expected_status
     *
     * @mbg.generated Tue Dec 05 13:47:12 CST 2017
     */
    public void setExpectedStatus(Short expectedStatus) {
        this.expectedStatus = expectedStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column global_transaction_process.service_name
     *
     * @return the value of global_transaction_process.service_name
     *
     * @mbg.generated Tue Dec 05 13:47:12 CST 2017
     */
    public String getServiceName() {
        return serviceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column global_transaction_process.service_name
     *
     * @param serviceName the value for global_transaction_process.service_name
     *
     * @mbg.generated Tue Dec 05 13:47:12 CST 2017
     */
    public void setServiceName(String serviceName) {
        this.serviceName = serviceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column global_transaction_process.version_name
     *
     * @return the value of global_transaction_process.version_name
     *
     * @mbg.generated Tue Dec 05 13:47:12 CST 2017
     */
    public String getVersionName() {
        return versionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column global_transaction_process.version_name
     *
     * @param versionName the value for global_transaction_process.version_name
     *
     * @mbg.generated Tue Dec 05 13:47:12 CST 2017
     */
    public void setVersionName(String versionName) {
        this.versionName = versionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column global_transaction_process.method_name
     *
     * @return the value of global_transaction_process.method_name
     *
     * @mbg.generated Tue Dec 05 13:47:12 CST 2017
     */
    public String getMethodName() {
        return methodName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column global_transaction_process.method_name
     *
     * @param methodName the value for global_transaction_process.method_name
     *
     * @mbg.generated Tue Dec 05 13:47:12 CST 2017
     */
    public void setMethodName(String methodName) {
        this.methodName = methodName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column global_transaction_process.rollback_method_name
     *
     * @return the value of global_transaction_process.rollback_method_name
     *
     * @mbg.generated Tue Dec 05 13:47:12 CST 2017
     */
    public String getRollbackMethodName() {
        return rollbackMethodName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column global_transaction_process.rollback_method_name
     *
     * @param rollbackMethodName the value for global_transaction_process.rollback_method_name
     *
     * @mbg.generated Tue Dec 05 13:47:12 CST 2017
     */
    public void setRollbackMethodName(String rollbackMethodName) {
        this.rollbackMethodName = rollbackMethodName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column global_transaction_process.retry_times
     *
     * @return the value of global_transaction_process.retry_times
     *
     * @mbg.generated Tue Dec 05 13:47:12 CST 2017
     */
    public Integer getRetryTimes() {
        return retryTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column global_transaction_process.retry_times
     *
     * @param retryTimes the value for global_transaction_process.retry_times
     *
     * @mbg.generated Tue Dec 05 13:47:12 CST 2017
     */
    public void setRetryTimes(Integer retryTimes) {
        this.retryTimes = retryTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column global_transaction_process.next_retry_time
     *
     * @return the value of global_transaction_process.next_retry_time
     *
     * @mbg.generated Tue Dec 05 13:47:12 CST 2017
     */
    public Date getNextRetryTime() {
        return nextRetryTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column global_transaction_process.next_retry_time
     *
     * @param nextRetryTime the value for global_transaction_process.next_retry_time
     *
     * @mbg.generated Tue Dec 05 13:47:12 CST 2017
     */
    public void setNextRetryTime(Date nextRetryTime) {
        this.nextRetryTime = nextRetryTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column global_transaction_process.created_at
     *
     * @return the value of global_transaction_process.created_at
     *
     * @mbg.generated Tue Dec 05 13:47:12 CST 2017
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column global_transaction_process.created_at
     *
     * @param createdAt the value for global_transaction_process.created_at
     *
     * @mbg.generated Tue Dec 05 13:47:12 CST 2017
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column global_transaction_process.updated_at
     *
     * @return the value of global_transaction_process.updated_at
     *
     * @mbg.generated Tue Dec 05 13:47:12 CST 2017
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column global_transaction_process.updated_at
     *
     * @param updatedAt the value for global_transaction_process.updated_at
     *
     * @mbg.generated Tue Dec 05 13:47:12 CST 2017
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}