package com.dyh.transaction.dao.model;

import java.util.Date;

public class GlobalTransactions {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column global_transactions.id
     *
     * @mbg.generated Tue Dec 05 13:47:12 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column global_transactions.status
     *
     * @mbg.generated Tue Dec 05 13:47:12 CST 2017
     */
    private Short status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column global_transactions.curr_sequence
     *
     * @mbg.generated Tue Dec 05 13:47:12 CST 2017
     */
    private Integer currSequence;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column global_transactions.created_at
     *
     * @mbg.generated Tue Dec 05 13:47:12 CST 2017
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column global_transactions.updated_at
     *
     * @mbg.generated Tue Dec 05 13:47:12 CST 2017
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column global_transactions.id
     *
     * @return the value of global_transactions.id
     *
     * @mbg.generated Tue Dec 05 13:47:12 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column global_transactions.id
     *
     * @param id the value for global_transactions.id
     *
     * @mbg.generated Tue Dec 05 13:47:12 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column global_transactions.status
     *
     * @return the value of global_transactions.status
     *
     * @mbg.generated Tue Dec 05 13:47:12 CST 2017
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column global_transactions.status
     *
     * @param status the value for global_transactions.status
     *
     * @mbg.generated Tue Dec 05 13:47:12 CST 2017
     */
    public void setStatus(Short status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column global_transactions.curr_sequence
     *
     * @return the value of global_transactions.curr_sequence
     *
     * @mbg.generated Tue Dec 05 13:47:12 CST 2017
     */
    public Integer getCurrSequence() {
        return currSequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column global_transactions.curr_sequence
     *
     * @param currSequence the value for global_transactions.curr_sequence
     *
     * @mbg.generated Tue Dec 05 13:47:12 CST 2017
     */
    public void setCurrSequence(Integer currSequence) {
        this.currSequence = currSequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column global_transactions.created_at
     *
     * @return the value of global_transactions.created_at
     *
     * @mbg.generated Tue Dec 05 13:47:12 CST 2017
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column global_transactions.created_at
     *
     * @param createdAt the value for global_transactions.created_at
     *
     * @mbg.generated Tue Dec 05 13:47:12 CST 2017
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column global_transactions.updated_at
     *
     * @return the value of global_transactions.updated_at
     *
     * @mbg.generated Tue Dec 05 13:47:12 CST 2017
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column global_transactions.updated_at
     *
     * @param updatedAt the value for global_transactions.updated_at
     *
     * @mbg.generated Tue Dec 05 13:47:12 CST 2017
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}